### PR TITLE
fix #176 - infinite loop on align syntax error inside AsmStatement

### LINKED ISSUE #176: infinite loop on align syntax error inside AsmStatement
This crashes all the tools based on dparse, when this error is made:

```d
asm
{
    align 2);
}
```

### PR DESCRIPTION
**Pull request by BBasile**
Please once merged also push the `v0.7.2-alpha.2` tag. D-Scanner and DCD need to get the dependency upgraded.

### CODE REVIEW

File: src/dparse/parser.d [hunk 1]
```diff
@@ -532,9 +532,20 @@ class Parser
             advance(); // align
             node.hasAlign = true;
             if (currentIsOneOf(tok!"intLiteral", tok!"identifier"))
+            {
                 node.identifierOrIntegerOrOpcode = advance();
+                if (!currentIs(tok!";"))
+                {
+                    error("';' expected.");
+                    advance();
+                    return null;
```
Comment (BBasile) [inline src/dparse/parser.d]: The loop was `while (stack.put(<the result of this>){ ... }`. The temp node was always returned.
